---
- name: Create the agent directory
  file:
    path: "{{ app_root }}/newrelic"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
  become: yes

- name: Download the agent and unzip it into place
  unarchive:
    src: "{{ agent_download_url }}/{{ agent_version }}/newrelic-java.zip"
    remote_src: yes
    dest: "{{ app_root }}"
    mode: "0755"
    list_files: yes
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
  become: yes
  tags:
    - new-relic

- name: Set up the New Relic config file
  template:
    src: "templates/newrelic.yml.j2"
    dest: "{{ app_root }}/newrelic/newrelic.yml"
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: "0640"
  become: yes
  tags:
    - new-relic
