---
- name: Create the agent directory
  file:
    path: "{{ server_root }}/newrelic"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
  become: yes

- name: Download the agent and unzip it into place
  unarchive:
    src: "{{ nr_java_agent_download_url }}"
    remote_src: yes
    dest: "{{ server_root }}"
    mode: "0755"
    list_files: yes
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
  become: yes
  tags:
    - new-relic

- name: Set up the New Relic config file
  template:
    src: "templates/newrelic.yml.j2"
    dest: "{{ server_root }}/newrelic/newrelic.yml"
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: "0640"
  become: yes
  tags:
    - new-relic
